name: testing 

on:
  push:
    branches:
      - testing 

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:

      - name: Set up source
        uses: actions/checkout@v4

      - name: Set up version
        run: echo "VERSION=$(awk -F\" '/^version =/ {print $2}' Cargo.toml)" >> $GITHUB_ENV

      - run: cargo build --release
      - run: ./target/release/release ${{ github.repository }} ${{ env.VERSION }} ${{ github.sha }}
